# Generated by Django 3.2.4 on 2021-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donarapp', '0002_remove_data_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sex',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
