# Generated by Django 3.2.4 on 2021-06-27 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donarapp', '0004_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='address',
        ),
        migrations.AddField(
            model_name='snippet',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
